<a href="https://colab.research.google.com/github/Jainadi2128/Python-Projects/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

## Creating Arrays

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([(1.5,2,3), (4,5,6)], dtype=float)
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [5]:
c = np.array([[(1.5,2,3),(4,5,6)], [(3,2,1),(4,5,6)]])
print(c)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


## Initial Placeholders

In [6]:
# Create an array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# Create an array of ones
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [8]:
# Create an array of evenly spaced values(step value)
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [9]:
# Create an array of eveny spaced values(number of samples)
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [10]:
# Create a constant array
e = np.full((3,3),9)
e

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [11]:
# Create a 2x2 identity matrix
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [12]:
# Create an array with random values
np.random.random((2,2))

array([[0.75630977, 0.48072661],
       [0.95443136, 0.07663821]])

In [13]:
# Create an empty array
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

## Saving and Loading on Disk

In [14]:
# np.save('my_array',a)
# np.savez('array.npz',a , b)
# np.load('my_array.npy')

## Saving and Loading Text Files

In [15]:
#np.loadtxt('myfile.txt')
#np.genfromtxt('myfile.csv', delimiter=',')
#np.savetxt('myarray.txt', a, delimiter=" ")

# Inspecting your array

In [16]:
# Array Dimensions
a.shape

(3,)

In [17]:
# length of array
len(a)

3

In [18]:
# Number of array dimensions
b.ndim

2

In [19]:
# Number of array elements
e.size

9

In [20]:
# Data type of array elements
b.dtype

dtype('float64')

In [21]:
# Name of data type
b.dtype.name

'float64'

In [22]:
# Convert an array to a different type
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

# Array Mathematics

## Arithmetic Operations

In [23]:
print(a)
print(b)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [24]:
# Subtraction
g = a-b
g
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [25]:
# Addition
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [26]:
# Division
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [27]:
# Multiplication
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [28]:
# Exponentiation
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [29]:
# Squareroot
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [30]:
# Logarithm
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [31]:
# Print sin and cos of arrays
print(np.sin(a))
print(np.cos(b))


[0.84147098 0.90929743 0.14112001]
[[ 0.0707372  -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [68]:
# Dot product
e = np.full((2,2),7)
e.dot(f)

array([[7., 7.],
       [7., 7.]])

In [71]:
# power
np.power(a,2)

array([1, 4, 9])

In [72]:
# floor value
np.floor(a)

array([1., 2., 3.])

In [73]:
# ceil value
np.ceil(b)

array([[2., 2., 3.],
       [4., 5., 6.]])

In [74]:
# absolute value
np.absolute(b)

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [75]:
# round value
np.round(b)

array([[2., 2., 3.],
       [4., 5., 6.]])

## Comparison

In [33]:
# Element wise comparison
a == b

array([[False,  True,  True],
       [False, False, False]])

In [34]:
# Element wise comparison
a < 2

array([ True, False, False])

In [35]:
# Array wise comparison
np.array_equal(a,b)

False

## Aggregate Functions

In [36]:
# Array-wise sum
a.sum()

6

In [37]:
# Array-wise minimum value
b.min()

1.5

In [38]:
# Maximum value of an array row
b.max(axis=0)

array([4., 5., 6.])

In [39]:
# Cumulative sum of the elements
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [40]:
# Mean
a.mean()

2.0

In [41]:
# Median
np.median(b)

3.5

In [42]:
# Correlation
np.corrcoef(a)

1.0

In [43]:
# standard deviation
np.std(b)

1.5920810978785667

In [44]:
# variance
np.var(b)

2.534722222222222

# Copying arrays

In [45]:
# Create a view of the array with the same data
h = a.view()
h

array([1, 2, 3])

In [46]:
# Create a copy of the array
np.copy(a)

array([1, 2, 3])

In [47]:
# Create a deep copy of the array
h = a.copy()
h

array([1, 2, 3])

# Sorting Arrays

In [48]:
# Sort an array
a.sort()

In [49]:
# Sort the elements of an array's axis
c.sort(axis=0)
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

# Subsetting, Slicing and Indexing

In [50]:
# Subsetting
# Select the element at the 2 index
a[2]

3

In [51]:
# Select the element at row 1 and column 2
b[1][2]

6.0

In [52]:
# Slicing
# Select items at index 0 and 1
a[0:2]

array([1, 2])

In [53]:
# Select items at rows 0 and 1 and column 1
b[0:2,1]

array([2., 5.])

In [54]:
# Select all items at row 0
b[:1]

array([[1.5, 2. , 3. ]])

In [55]:
# Boolean indexing
a[a<2]

array([1])

# Array Manipulation

In [56]:
# #Permute array dimensions
i = np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [57]:
# Changing Array shape
# Flatten the array, Reshape but don't change the data
print(b.ravel())
print(g.reshape(3,-2))

[1.5 2.  3.  4.  5.  6. ]
[[-0.5  0. ]
 [ 0.  -3. ]
 [-3.  -3. ]]


In [58]:
# Adding/ Removing Elements
# 1. Return a new array with shape (2,6)
np.resize(h,(2,6))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [59]:
# 2. Append items to an array
np.append(h,g)

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [60]:
# Insert items in an array
np.insert(a,1,5)
# a = array name
# 2 argument = index position of the array
# 3 argument = the value at the specified index in the array

array([1, 5, 2, 3])

In [61]:
# Delete items from an array
np.delete(a, (1))

array([1, 3])

In [62]:
# Combining Arrays
# Concatenate Arrays
np.concatenate((a,d), axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [63]:
# Stack arrays vertically (row-wise)
np.vstack((a,b))
# np.r_[e,f]

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [64]:
# Stack arrays horizontally (column-wise)
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [65]:
# Create stacked column wise arrays
np.column_stack((a,d))
# np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [66]:
## Splitting Arrays
# Split the array horizontally at 3 index
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [67]:
# Split the array vertically at 2 index
np.vsplit(c,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]