<a href="https://colab.research.google.com/github/Jainadi2128/Python-Projects/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Creating Arrays
a = np.array([1,2,3])
b = np.array([(1.5,2,3),(4,5,6)],dtype=float)
c = np.array([[(1.5,2,3),(4,5,6)], [(3,2,1),(4,5,6)]],dtype=float)

In [7]:
print(a)
print(b)
print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [9]:
# Initial Placeholders
# Creates an array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# Creates an array of ones
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
# Creates an array of evenly placed values(step values)
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [15]:
#  Creates an array of evenly spaced values(number of samples) 
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
# create a constant array
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [17]:
# create a 2x2 identity matrix
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [18]:
# Create an array with random values
np.random.random((2,2))

array([[0.15560748, 0.32380136],
       [0.91399762, 0.53462775]])

In [19]:
# Create an empty array
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [20]:
## Saving and Loading on Disk
np.save('my_array',a)

In [21]:
np.savez('array.npz',a,b)

In [22]:
np.load('my_array.npy')

array([1, 2, 3])

In [26]:
## Saving and Loading Text Files
#np.loadtxt('myfile'.txt)
#np.genfromtxt('my_file.csv', delimiter=',')
#np.savetxt('my_array.txt',a,delimiter=" ")

In [27]:
## Inspecting array
# Array dimensions
a.shape


(3,)

In [28]:
# Length of array
len(a)

3

In [29]:
# Number of array dimensions
b.ndim

2

In [30]:
# number of array elements
e.size

4

In [31]:
# Data type of array elements
b.dtype

dtype('float64')

In [32]:
# Name of datatype
np.dtype.name

<attribute 'name' of 'numpy.dtype' objects>

In [33]:
# Convert an array to a different type
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
## Asking for help
np.info(np.ndarray.dtype)

In [35]:
## Array Mathematics
# Arithmetic Operations
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [36]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [37]:
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [38]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [39]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [40]:
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [42]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [43]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [44]:
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [45]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [46]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

In [47]:
# Comparison
a == b

array([[False,  True,  True],
       [False, False, False]])

In [48]:
a < 2

array([ True, False, False])

In [49]:
np.array_equal(a,b)

False

In [50]:
## Aggregate Functions
# Array wise sum
a.sum()

6

In [51]:
# Array wise minimum value
a.min()

1

In [52]:
a.mean()

2.0

In [57]:
#a.median()

In [58]:
#a.corrcoef()

In [59]:
np.std(b)



1.5920810978785667

In [61]:
## Copying Arrays
h = a.view()
h

array([1, 2, 3])

In [62]:
np.copy(a)

array([1, 2, 3])

In [64]:
h = a.copy()
h

array([1, 2, 3])

In [67]:
## Sorting Arrays
a.sort()

In [68]:
c.sort(axis=0)

In [69]:
## Subsetting, Slicing and Indexing
# Subsetting
a[2]

3

In [70]:
b[1,2]

6.0

In [71]:
# Slicing
a[0:2]

array([1, 2])

In [72]:
b[0:2,1]

array([2., 5.])

In [74]:
a[::-1]

array([3, 2, 1])

In [75]:
## Array Manipulation
# Transposing Array
i = np.transpose(b)
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])